from django.urls import path

from .views import (
    CampanhaPublicView,
    CampanhaPublicStep1SubmitView,
    CampanhaPublicStep2SubmitView,
    CampanhaPublicStep3SubmitView,
    CampanhaPublicStep4SubmitView,
    CampanhaPublicStep5SubmitView,
    CampanhaPublicStep6SubmitView,
    CampanhaPublicStep7SubmitView,
    CampanhaPublicStep8SubmitView,
    CampanhaPublicStep9SubmitView,
    CanalDenunciasPublicView,
    CampanhaDetailView,
    CampanhaListCreateView,
    CampanhaMedidaPreliminarDetailView,
    CampanhaMedidaPreliminarListCreateView,
    CampanhaQuandoPreliminarDetailView,
    CampanhaQuandoPreliminarUpsertView,
    CampanhaRelatorioView,
    CampanhaRelatorioAnexoDetailView,
    CampanhaRelatorioAnexoListCreateView,
    CampanhaRelatorioPdfView,
    ConsultorDetailView,
    ConsultorListCreateView,
    ConsultoriaConfiguracaoView,
    ConsultoriaResponsavelTecnicoDetailView,
    ConsultoriaResponsavelTecnicoListCreateView,
    CargoDetailView,
    CargoListCreateView,
    EmpresaDetailView,
    EmpresaCanalDenunciasLinkView,
    EmpresaCanalDenunciasListView,
    EmpresaCanalDenunciaDetailView,
    EmpresaCanalDenunciaAtualizacaoCreateView,
    EmpresaInativarView,
    EmpresaTotemLinkView,
    EmpresaListCreateView,
    DashboardOverviewView,
    GheDetailView,
    GheListCreateView,
    LoginView,
    MeView,
    SetorDetailView,
    SetorListCreateView,
    TotemPublicView,
    healthcheck,
)

urlpatterns = [
    path('health/', healthcheck, name='healthcheck'),
    path('auth/login/', LoginView.as_view(), name='login'),
    path('auth/me/', MeView.as_view(), name='me'),
    path('dashboard/overview/', DashboardOverviewView.as_view(), name='dashboard-overview'),
    path('consultoria-configuracao/', ConsultoriaConfiguracaoView.as_view(), name='consultoria-configuracao'),
    path('consultoria-configuracao/responsaveis-tecnicos/', ConsultoriaResponsavelTecnicoListCreateView.as_view(), name='consultoria-responsavel-tecnico-list-create'),
    path('consultoria-configuracao/responsaveis-tecnicos/<int:tecnico_id>/', ConsultoriaResponsavelTecnicoDetailView.as_view(), name='consultoria-responsavel-tecnico-detail'),
    path('consultores/', ConsultorListCreateView.as_view(), name='consultor-list-create'),
    path('consultores/<int:consultor_id>/', ConsultorDetailView.as_view(), name='consultor-detail'),
    path('empresas/', EmpresaListCreateView.as_view(), name='empresa-list-create'),
    path('empresas/<int:empresa_id>/', EmpresaDetailView.as_view(), name='empresa-detail'),
    path('empresas/<int:empresa_id>/inativar/', EmpresaInativarView.as_view(), name='empresa-inativar'),
    path('empresas/<int:empresa_id>/canal-denuncias-link/', EmpresaCanalDenunciasLinkView.as_view(), name='empresa-canal-denuncias-link'),
    path('empresas/<int:empresa_id>/totem-link/', EmpresaTotemLinkView.as_view(), name='empresa-totem-link'),
    path('empresas/<int:empresa_id>/canal-denuncias/', EmpresaCanalDenunciasListView.as_view(), name='empresa-canal-denuncias-list'),
    path('empresas/<int:empresa_id>/canal-denuncias/<int:denuncia_id>/', EmpresaCanalDenunciaDetailView.as_view(), name='empresa-canal-denuncias-detail'),
    path('empresas/<int:empresa_id>/canal-denuncias/<int:denuncia_id>/atualizacoes/', EmpresaCanalDenunciaAtualizacaoCreateView.as_view(), name='empresa-canal-denuncias-atualizacao-create'),
    path('totem/public/<uuid:token>/', TotemPublicView.as_view(), name='totem-public'),
    path('canal-denuncias/public/<uuid:token>/', CanalDenunciasPublicView.as_view(), name='canal-denuncias-public'),
    path('setores/', SetorListCreateView.as_view(), name='setor-list-create'),
    path('setores/<int:setor_id>/', SetorDetailView.as_view(), name='setor-detail'),
    path('ghes/', GheListCreateView.as_view(), name='ghe-list-create'),
    path('ghes/<int:ghe_id>/', GheDetailView.as_view(), name='ghe-detail'),
    path('cargos/', CargoListCreateView.as_view(), name='cargo-list-create'),
    path('cargos/<int:cargo_id>/', CargoDetailView.as_view(), name='cargo-detail'),
    path('campanhas/', CampanhaListCreateView.as_view(), name='campanha-list-create'),
    path('campanhas/<int:campanha_id>/', CampanhaDetailView.as_view(), name='campanha-detail'),
    path('campanhas/<int:campanha_id>/relatorio/', CampanhaRelatorioView.as_view(), name='campanha-relatorio'),
    path('campanhas/<int:campanha_id>/relatorio/pdf/', CampanhaRelatorioPdfView.as_view(), name='campanha-relatorio-pdf'),
    path('campanhas/<int:campanha_id>/relatorio-anexos/', CampanhaRelatorioAnexoListCreateView.as_view(), name='campanha-relatorio-anexo-list-create'),
    path('campanhas/<int:campanha_id>/relatorio-anexos/<int:anexo_id>/', CampanhaRelatorioAnexoDetailView.as_view(), name='campanha-relatorio-anexo-detail'),
    path('campanhas/<int:campanha_id>/medidas-preliminares/', CampanhaMedidaPreliminarListCreateView.as_view(), name='campanha-medidas-preliminares-list-create'),
    path('campanhas/<int:campanha_id>/medidas-preliminares/<int:medida_id>/', CampanhaMedidaPreliminarDetailView.as_view(), name='campanha-medidas-preliminares-detail'),
    path('campanhas/<int:campanha_id>/quandos-preliminares/', CampanhaQuandoPreliminarUpsertView.as_view(), name='campanha-quandos-preliminares-upsert'),
    path('campanhas/<int:campanha_id>/quandos-preliminares/<int:quando_id>/', CampanhaQuandoPreliminarDetailView.as_view(), name='campanha-quandos-preliminares-detail'),
    path('campanhas/public/<uuid:share_token>/', CampanhaPublicView.as_view(), name='campanha-public-detail'),
    path('campanhas/public/<uuid:share_token>/step1/', CampanhaPublicStep1SubmitView.as_view(), name='campanha-public-step1-submit'),
    path('campanhas/public/<uuid:share_token>/step2/', CampanhaPublicStep2SubmitView.as_view(), name='campanha-public-step2-submit'),
    path('campanhas/public/<uuid:share_token>/step3/', CampanhaPublicStep3SubmitView.as_view(), name='campanha-public-step3-submit'),
    path('campanhas/public/<uuid:share_token>/step4/', CampanhaPublicStep4SubmitView.as_view(), name='campanha-public-step4-submit'),
    path('campanhas/public/<uuid:share_token>/step5/', CampanhaPublicStep5SubmitView.as_view(), name='campanha-public-step5-submit'),
    path('campanhas/public/<uuid:share_token>/step6/', CampanhaPublicStep6SubmitView.as_view(), name='campanha-public-step6-submit'),
    path('campanhas/public/<uuid:share_token>/step7/', CampanhaPublicStep7SubmitView.as_view(), name='campanha-public-step7-submit'),
    path('campanhas/public/<uuid:share_token>/step8/', CampanhaPublicStep8SubmitView.as_view(), name='campanha-public-step8-submit'),
    path('campanhas/public/<uuid:share_token>/step9/', CampanhaPublicStep9SubmitView.as_view(), name='campanha-public-step9-submit'),
]
