from django.urls import path

from .views import (
    CampanhaPublicView,
    CampanhaPublicStep1SubmitView,
    CampanhaPublicStep2SubmitView,
    CampanhaPublicStep3SubmitView,
    CampanhaPublicStep4SubmitView,
    CampanhaPublicStep5SubmitView,
    CampanhaPublicStep6SubmitView,
    CampanhaPublicStep7SubmitView,
    CampanhaPublicStep8SubmitView,
    CampanhaPublicStep9SubmitView,
    CampanhaDetailView,
    CampanhaListCreateView,
    ConsultorDetailView,
    ConsultorListCreateView,
    CargoDetailView,
    CargoListCreateView,
    EmpresaDetailView,
    EmpresaInativarView,
    EmpresaListCreateView,
    GheDetailView,
    GheListCreateView,
    LoginView,
    MeView,
    SetorDetailView,
    SetorListCreateView,
    healthcheck,
)

urlpatterns = [
    path('health/', healthcheck, name='healthcheck'),
    path('auth/login/', LoginView.as_view(), name='login'),
    path('auth/me/', MeView.as_view(), name='me'),
    path('consultores/', ConsultorListCreateView.as_view(), name='consultor-list-create'),
    path('consultores/<int:consultor_id>/', ConsultorDetailView.as_view(), name='consultor-detail'),
    path('empresas/', EmpresaListCreateView.as_view(), name='empresa-list-create'),
    path('empresas/<int:empresa_id>/', EmpresaDetailView.as_view(), name='empresa-detail'),
    path('empresas/<int:empresa_id>/inativar/', EmpresaInativarView.as_view(), name='empresa-inativar'),
    path('setores/', SetorListCreateView.as_view(), name='setor-list-create'),
    path('setores/<int:setor_id>/', SetorDetailView.as_view(), name='setor-detail'),
    path('ghes/', GheListCreateView.as_view(), name='ghe-list-create'),
    path('ghes/<int:ghe_id>/', GheDetailView.as_view(), name='ghe-detail'),
    path('cargos/', CargoListCreateView.as_view(), name='cargo-list-create'),
    path('cargos/<int:cargo_id>/', CargoDetailView.as_view(), name='cargo-detail'),
    path('campanhas/', CampanhaListCreateView.as_view(), name='campanha-list-create'),
    path('campanhas/<int:campanha_id>/', CampanhaDetailView.as_view(), name='campanha-detail'),
    path('campanhas/public/<uuid:share_token>/', CampanhaPublicView.as_view(), name='campanha-public-detail'),
    path('campanhas/public/<uuid:share_token>/step1/', CampanhaPublicStep1SubmitView.as_view(), name='campanha-public-step1-submit'),
    path('campanhas/public/<uuid:share_token>/step2/', CampanhaPublicStep2SubmitView.as_view(), name='campanha-public-step2-submit'),
    path('campanhas/public/<uuid:share_token>/step3/', CampanhaPublicStep3SubmitView.as_view(), name='campanha-public-step3-submit'),
    path('campanhas/public/<uuid:share_token>/step4/', CampanhaPublicStep4SubmitView.as_view(), name='campanha-public-step4-submit'),
    path('campanhas/public/<uuid:share_token>/step5/', CampanhaPublicStep5SubmitView.as_view(), name='campanha-public-step5-submit'),
    path('campanhas/public/<uuid:share_token>/step6/', CampanhaPublicStep6SubmitView.as_view(), name='campanha-public-step6-submit'),
    path('campanhas/public/<uuid:share_token>/step7/', CampanhaPublicStep7SubmitView.as_view(), name='campanha-public-step7-submit'),
    path('campanhas/public/<uuid:share_token>/step8/', CampanhaPublicStep8SubmitView.as_view(), name='campanha-public-step8-submit'),
    path('campanhas/public/<uuid:share_token>/step9/', CampanhaPublicStep9SubmitView.as_view(), name='campanha-public-step9-submit'),
]
