# Generated by Django 6.0.1 on 2026-02-22 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], max_length=4)),
                ('document_number', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('establishment_type', models.CharField(choices=[('FILIAL', 'Filial'), ('UNIDADE', 'Unidade'), ('MATRIZ', 'Matriz'), ('OUTRO', 'Outro')], max_length=10)),
                ('establishment_custom_name', models.CharField(blank=True, max_length=120)),
                ('establishment_name', models.CharField(max_length=255)),
                ('evaluation_type', models.CharField(choices=[('SETOR', 'Setor'), ('GHE', 'GHE')], default='SETOR', max_length=8)),
                ('responsible_name', models.CharField(max_length=255)),
                ('risk_level', models.CharField(max_length=20)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('postal_code', models.CharField(blank=True, max_length=12)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('street', models.CharField(blank=True, max_length=180)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('complement', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas_consultoria', to=settings.AUTH_USER_MODEL)),
                ('responsavel_usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='empresa_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-created_at'],
            },
        ),
    ]
