# Generated by Django 6.0.1 on 2026-02-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='ghes',
            field=models.ManyToManyField(blank=True, related_name='cargos', to='core.ghe'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='setores',
            field=models.ManyToManyField(blank=True, related_name='cargos', to='core.setor'),
        ),
    ]
