# Generated by Django 6.0.1 on 2026-02-22 04:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_campanha'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='qr_code_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campanha',
            name='share_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
