# Generated by Django 6.0.1 on 2026-02-22 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_campanha_qr_code_data_campanha_share_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaRespostaStep1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro nao informar')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step1_respostas', to='core.campanha')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanha_step1_respostas', to='core.cargo')),
                ('ghe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanha_step1_respostas', to='core.ghe')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanha_step1_respostas', to='core.setor')),
            ],
            options={
                'verbose_name': 'Resposta Step 1',
                'verbose_name_plural': 'Respostas Step 1',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campanha', 'cpf'], name='core_campan_campanh_97b1c3_idx')],
            },
        ),
    ]
