# Generated by Django 6.0.1 on 2026-02-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_campanharespostastep1'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanharespostastep1',
            name='cpf_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='campanharespostastep1',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf_hash', ''), _negated=True), fields=('campanha', 'cpf_hash'), name='uniq_campanha_cpf_hash_step1'),
        ),
    ]
