# Generated by Django 6.0.1 on 2026-02-22 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_campanharespostastep1_cpf_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaRespostaStep2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(choices=[('NUNCA', 'Nunca'), ('RARAMENTE', 'Raramente'), ('AS_VEZES', 'As vezes'), ('FREQUENTEMENTE', 'Frequentemente'), ('SEMPRE', 'Sempre')], max_length=20)),
                ('q2', models.CharField(choices=[('NUNCA', 'Nunca'), ('RARAMENTE', 'Raramente'), ('AS_VEZES', 'As vezes'), ('FREQUENTEMENTE', 'Frequentemente'), ('SEMPRE', 'Sempre')], max_length=20)),
                ('q3', models.CharField(choices=[('NUNCA', 'Nunca'), ('RARAMENTE', 'Raramente'), ('AS_VEZES', 'As vezes'), ('FREQUENTEMENTE', 'Frequentemente'), ('SEMPRE', 'Sempre')], max_length=20)),
                ('q4', models.CharField(choices=[('NUNCA', 'Nunca'), ('RARAMENTE', 'Raramente'), ('AS_VEZES', 'As vezes'), ('FREQUENTEMENTE', 'Frequentemente'), ('SEMPRE', 'Sempre')], max_length=20)),
                ('q5', models.CharField(choices=[('NUNCA', 'Nunca'), ('RARAMENTE', 'Raramente'), ('AS_VEZES', 'As vezes'), ('FREQUENTEMENTE', 'Frequentemente'), ('SEMPRE', 'Sempre')], max_length=20)),
                ('q6', models.CharField(choices=[('NUNCA', 'Nunca'), ('RARAMENTE', 'Raramente'), ('AS_VEZES', 'As vezes'), ('FREQUENTEMENTE', 'Frequentemente'), ('SEMPRE', 'Sempre')], max_length=20)),
                ('q7', models.CharField(choices=[('NUNCA', 'Nunca'), ('RARAMENTE', 'Raramente'), ('AS_VEZES', 'As vezes'), ('FREQUENTEMENTE', 'Frequentemente'), ('SEMPRE', 'Sempre')], max_length=20)),
                ('q8', models.CharField(choices=[('NUNCA', 'Nunca'), ('RARAMENTE', 'Raramente'), ('AS_VEZES', 'As vezes'), ('FREQUENTEMENTE', 'Frequentemente'), ('SEMPRE', 'Sempre')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step2', to='core.campanharespostastep1')),
            ],
            options={
                'verbose_name': 'Resposta Step 2',
                'verbose_name_plural': 'Respostas Step 2',
                'ordering': ['-created_at'],
            },
        ),
    ]
