# Generated by Django 6.0.1 on 2026-02-22 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_campanharespostastep8'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaRespostaStep9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step9', to='core.campanharespostastep1')),
            ],
            options={
                'verbose_name': 'Resposta Step 9',
                'verbose_name_plural': 'Respostas Step 9',
                'ordering': ['-created_at'],
            },
        ),
    ]
