# Generated by Django 6.0.1 on 2026-02-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_campanharespostastep9'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='campanharespostastep1',
            name='uniq_campanha_cpf_hash_step1',
        ),
        migrations.AddField(
            model_name='campanharespostastep1',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='campanharespostastep1',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('cpf_hash', ''), _negated=True), ('is_completed', True)), fields=('campanha', 'cpf_hash'), name='uniq_campanha_cpf_hash_step1'),
        ),
    ]
