# Generated by Django 6.0.1 on 2026-02-22 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_campanharespostastep1_uniq_campanha_cpf_hash_step1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaMedidaPreliminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField()),
                ('question_field', models.CharField(max_length=10)),
                ('scope_type', models.CharField(choices=[('GERAL', 'Geral'), ('SETOR', 'Setor'), ('GHE', 'GHE')], default='GERAL', max_length=10)),
                ('action_text', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas_preliminares', to='core.campanha')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidas_preliminares_criadas', to=settings.AUTH_USER_MODEL)),
                ('ghe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medidas_preliminares', to='core.ghe')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medidas_preliminares', to='core.setor')),
            ],
            options={
                'verbose_name': 'Medida preliminar',
                'verbose_name_plural': 'Medidas preliminares',
                'ordering': ['step_number', 'question_field', '-created_at'],
                'indexes': [models.Index(fields=['campanha', 'step_number', 'question_field'], name='core_campan_campanh_91569e_idx'), models.Index(fields=['campanha', 'scope_type'], name='core_campan_campanh_3b7607_idx')],
            },
        ),
    ]
