# Generated by Django 6.0.1 on 2026-02-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_campanhamedidapreliminar'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanhamedidapreliminar',
            name='when_months',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
