# Generated by Django 6.0.1 on 2026-02-22 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_campanhamedidapreliminar_when_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaQuandoPreliminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField()),
                ('question_field', models.CharField(max_length=10)),
                ('scope_type', models.CharField(choices=[('GERAL', 'Geral'), ('SETOR', 'Setor'), ('GHE', 'GHE')], default='GERAL', max_length=10)),
                ('when_months', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quandos_preliminares', to='core.campanha')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quandos_preliminares_criados', to=settings.AUTH_USER_MODEL)),
                ('ghe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quandos_preliminares', to='core.ghe')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quandos_preliminares', to='core.setor')),
            ],
            options={
                'verbose_name': 'Quando preliminar',
                'verbose_name_plural': 'Quandos preliminares',
                'ordering': ['step_number', 'question_field'],
                'constraints': [models.UniqueConstraint(fields=('campanha', 'step_number', 'question_field', 'scope_type', 'setor', 'ghe'), name='uniq_quando_preliminar_por_pergunta_escopo')],
            },
        ),
    ]
