# Generated by Django 6.0.1 on 2026-02-22 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_campanhaquandopreliminar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaRelatorioAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_key', models.CharField(max_length=600, unique=True)),
                ('file_url', models.URLField(max_length=900)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio_anexos', to='core.campanha')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorio_anexos_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo de relatorio',
                'verbose_name_plural': 'Anexos de relatorio',
                'ordering': ['-created_at'],
            },
        ),
    ]
