# Generated by Django 6.0.2 on 2026-02-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_campanharelatorioanexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='review_recommendation_months',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
