# Generated by Django 6.0.1 on 2026-02-22 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_campanha_review_recommendation_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultoriaConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, max_length=20)),
                ('nome_consultoria', models.CharField(blank=True, max_length=255)),
                ('responsavel_legal', models.CharField(blank=True, max_length=255)),
                ('representante_legal_relatorio', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultoria_configuracao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuracao da Consultoria',
                'verbose_name_plural': 'Configuracoes da Consultoria',
            },
        ),
        migrations.CreateModel(
            name='ConsultoriaResponsavelTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('formacao', models.CharField(max_length=255)),
                ('registro', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis_tecnicos', to='core.consultoriaconfiguracao')),
            ],
            options={
                'verbose_name': 'Responsavel Tecnico da Consultoria',
                'verbose_name_plural': 'Responsaveis Tecnicos da Consultoria',
                'ordering': ['id'],
            },
        ),
    ]
