# Generated by Django 6.0.1 on 2026-02-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_consultoriaconfiguracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultoriaconfiguracao',
            name='cidade',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='consultoriaconfiguracao',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
