# Generated by Django 6.0.1 on 2026-02-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_user_access_expires_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghe',
            name='setores',
            field=models.ManyToManyField(blank=True, related_name='ghes', to='core.setor'),
        ),
    ]
