# Generated by Django 6.0.2 on 2026-03-02 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_registrohumor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanharespostastep1',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=1),
        ),
        migrations.AlterField(
            model_name='canaldenuncia',
            name='tipo',
            field=models.CharField(choices=[('ASSEDIO_MORAL', 'Assédio moral'), ('ASSEDIO_SEXUAL', 'Assédio sexual'), ('DISCRIMINACAO', 'Discriminação'), ('VIOLENCIA_VERBAL', 'Violência verbal'), ('VIOLENCIA_FISICA', 'Violência física'), ('FRAUDE', 'Fraude'), ('CORRUPCAO', 'Corrupção'), ('DESVIO_CONDUTA', 'Desvio de conduta'), ('CONFLITO_INTERESSE', 'Conflito de interesse'), ('OUTROS', 'Outros')], default='OUTROS', max_length=40),
        ),
        migrations.CreateModel(
            name='PedidoAjuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('contato', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_ajuda', to='core.empresa')),
                ('funcao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_ajuda', to='core.cargo')),
                ('ghe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_ajuda', to='core.ghe')),
            ],
            options={
                'verbose_name': 'Pedido de Ajuda',
                'verbose_name_plural': 'Pedidos de Ajuda',
                'ordering': ['-created_at'],
            },
        ),
    ]
