# Generated by Django 6.0.2 on 2026-03-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_campanharespostastep1_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultoriaresponsaveltecnico',
            name='responsavel_totem',
            field=models.BooleanField(default=False),
        ),
    ]
