# Generated by Django 6.0.2 on 2026-03-12 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_campanhaplanoacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consultoria_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultoria_usuarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
