# Generated by Django 6.0.2 on 2026-03-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_user_consultoria_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='document_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(fields=('consultor', 'document_number'), name='uniq_empresa_documento_por_consultoria'),
        ),
    ]
