# Generated by Django 6.0.2 on 2026-03-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_empresa_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='empresa_logos/'),
        ),
    ]
