# Generated by Django 6.0.2 on 2026-03-12 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_empresa_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='canaldenuncia',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canal_denuncias', to='core.setor'),
        ),
    ]
