# Generated by Django 6.0.3 on 2026-03-13 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_canaldenuncia_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoajuda',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_ajuda', to='core.setor'),
        ),
    ]
