# Generated by Django 6.0.3 on 2026-03-28 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_consultoriaconfiguracao_notify_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultoriaconfiguracao',
            name='notify_on_denuncia',
        ),
        migrations.RemoveField(
            model_name='consultoriaconfiguracao',
            name='notify_on_pedido_ajuda',
        ),
    ]
